// SPDX-License-Identifier: MPL-2.0
/**
 * @file
 * @copyright
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * @author Thomas Vogt, thomas@thomas-vogt.de
 *
 * @brief Declaration of Namespace Arinc649Qt.
 **/

/**
 * @dir
 * @brief Declaration/ Definition of Namespace Arinc649Qt.
 *
 * @sa Namespace @ref Arinc649Qt
 **/

#ifndef ARINC_649_QT_ARINC649QT_HPP
#define ARINC_649_QT_ARINC649QT_HPP

#include <spdlog/spdlog.h>

#include <arinc_649_qt/arinc_649_qt_export.h>

/**
 * @brief ARINC 649 Qt Adoptions.
 *
 * This namespace provides classes for the @ref Arinc649 implementation to interact with the Qt Framework.
 *
 * Provides:
 *  - A _Check Value Type_ Model (@ref CheckValueTypeModel).
 **/
namespace Arinc649Qt {

class CheckValueTypeModel;

/**
 * @brief Set the logging level for the ARINC 649 Qt Library.
 *
 * Adjusts the verbosity of log messages generated by the ARINC 649 Qt Library.
 *
 * @param level Logging level to be set.
 *   The level defines the granularity of log messages.
 **/
ARINC_649_QT_EXPORT void setLogLevel( spdlog::level::level_enum level );

}

#endif
