// SPDX-License-Identifier: MPL-2.0
/**
 * @file
 * @copyright
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * @author Thomas Vogt, thomas@thomas-vogt.de
 *
 * @brief Declaration of Namespace HelperQt.
 **/

/**
 * @dir
 * @brief Declaration/ Definition of Namespace HelperQt.
 *
 * @sa Namespace @ref HelperQt
 **/

#ifndef HELPER_QT_HELPERQT_HPP
#define HELPER_QT_HELPERQT_HPP

#include <helper_qt/helper_qt_export.h>

#include <helper/Helper.hpp>

#include <spdlog/spdlog.h>

/**
 * @brief Common Qt Utilities.
 *
 * The Helper Library provides common implementations for usual tasks.
 *
 **/
namespace HelperQt {

class EndianModel;
class VersionsModel;
class AboutDialog;

/**
 * @brief Return the Version Information for the Qt Library.
 *
 * @return Version Information of the Qt Library.
 **/
[[nodiscard]] HELPER_QT_EXPORT Helper::VersionsInformation::value_type qtVersion();

/**
 * @brief Set the logging level for the Helper Qt Library.
 *
 * Adjusts the verbosity of log messages generated by the Helper Qt Library.
 *
 * @param level Logging level to be set.
 *   The level defines the granularity of log messages.
 **/
HELPER_QT_EXPORT void setLogLevel( spdlog::level::level_enum level );

}

#endif
