= arinc_615a_operation-find(1)
Thomas Vogt

== Name

arinc_615a_operation-find - executes ARINC 615A FIND query.

== Synopsis

*arinc_615a_operation*
--operation=_Find_
[--target-address=_ip_]
[--dynamic-port]
[--timeout=_timeout_]
[--local-find-address=_ip_]
[--find-port=_port_]
[--targets-list=_targets list file_]

== Description
Initiates the _ARINC 615A FIND Operation_.
It lists all available _ARINC 615A Targets_.

== Options

// tag::options[]
*--target-address*=_IP_::
Target IP Address to query.
Defaults to `255.255.255.255`

*--dynamic-port*::
If this option is set, the IP stack selects the source port dynamically.
Otherwise, a fixed FIND UDP Port is used.

*--timeout*=_timeout_::
Wait for *timeout* seconds for a response.
If not set, the default (3 seconds) is used.

*--local-find-address*=_ip_::
Local IP address to bind.
If not set, the default `0.0.0.0` is used.

*--find-port*=_port_::
UDP FIND port.
If not set, the default port `1001` is used.

*--targets-list*=_targets list file_::
Path to the _Targets List_ JSON file.

== See Also

link:[arinc_615a_operation(1)]
link:[arinc_615a_operation-list-targets(1)]
