= arinc_615a_operation-information(1)
Thomas Vogt

== Name

arinc_615a_operation-information - executes ARINC 615A Information operation.

== Synopsis

*arinc_615a_operation*
--operation=_Information_
[-l|--log-level=_log-level_]
[-a|--target-address=_IP-Address_]
[-l|--targets-list=_File_]
[-i|--target-id=_Target ID_]
[--dlp-timeout=_Timeout_]
[--port-option]
[--local-tftp-address=_IP-Address_]
[--dlp-retries=_Retries_]
[--log-protocol-files[=true|false]]
[-p|--server-port=_Port_]
[-t|--tftp-timeout=_Timeout_]
[-d|--dally[=*true*|*false*]]
[-b|--block-size-option[=_Block Size_]]
[-i|--timeout-option[=_Timeout_]]
[-s|--handle-transfer-size-option[=*true*|*false*]]

== Description
Initiates the _ARINC 615A Information Operation_ to the given target.
If the operation succeeds, the _Load Configuration List_ is printed to the console.

== Options

// tag::options[]

.ARINC 615A Information Operation Options
*-l, --log-level*=_log-level_::
The verbosity of the logging information:
+
--
- trace
- debug
- info
- warn
- err
- critical
- off
--
Defaults to `warn`.

*-a, --target-address*=_IP_::
IP address of target hardware.

*-l, --targets-list*=_File_::
List of targets JSON file to map Target IDs to IP addresses.

*-i, --target-id*=_Target ID_::
ARINC 615A Target ID.

*--dlp-timeout*=_Timeout_::
The Timeout in seconds, when the protocol expects the transmission of a status information.
Defaults to `13` seconds.

*--port-option*::
Enables the ARINC 615A-3 Port Option.
If set, the host uses a dynamic TFTP port.

.ARINC 615A Options
*--local-tftp-address*=_IP-Address_::
Local interface IP address where the TFTP server binds to.
Defaults to `0.0.0.0`.

*--dlp-retries*=_Retries_::
DLP retries.
Defaults to `2`.

*--log-protocol-files*=[true|false]::
Enables logging of received and transmitted protocol files.

.TFTP Options
*-p|--server-port*=_Port_::
UDP port where the TFTP server is listen on.
Defaults to `59`.

*-t|--tftp-timeout*=_Timeout_::
Default TFTP packet timeout in seconds, when no timeout option is negotiated.
Defaults to `2` seconds.

*-d|--dally*=[*true*|*false*]::
TFTP dally option.
Wait when the last _ACK_ has been sent to prevent aborts on packet transmission errors on last packets.
If the parameter value is not provided, _true_ is assumed.

.TFTP Option Negotiation Options
*-b|--block-size-option*=[_Block Size_]::
Negotiates the TFTP block size for transfers.
Valid values must be between [8,65464].
If the _Block Size_ parameter is not provided, the block-size option is set to `1486` bytes.

*-i|--timeout-option*=[_Timeout_]::
Handles the TFTP timeout option negotiation with the given timeout in seconds.
Valid values must be between [1,255].
If the _timeout_ parameter is not provided, the timeout option is set to ``2`` seconds.

*-s|--handle-transfer-size-option*=[{*true*|*false*}]::
Handles the TFTP transfer size option negotiation.
Defaults to `true`.

// end::options[]

== Examples

.Basic query by IP address and Target ID
[source,shell]
----
arinc_615a_operation \
  --operation=Information \
  --target-address=192.168.1.50 \
  --target-id=ABCDEF_123
----

.Using a targets list JSON to resolve IP from Target ID
[source,shell]
----
arinc_615a_operation \
  --operation=Information \
  --targets-list=targets.json \
  --target-id=ABCDEF_123
----

.Binding the local TFTP server and enabling the ARINC 615A-3 Port Option
[source,shell]
----
arinc_615a_operation \
  --operation=Information \
  --target-address=192.168.1.50 \
  --target-id=ABCDEF_123 \
  --local-tftp-address=192.168.1.10 \
  --server-port=59 \
  --port-option
----

.Adjusting timeouts and log verbosity
[source,shell]
----
arinc_615a_operation \
  --operation=Information \
  --target-address=192.168.1.50 \
  --target-id=ABCDEF_123 \
  --dlp-timeout=20 \
  --tftp-timeout=3 \
  --timeout-option=3 \
  --log-level=info
----

== See Also

link:[arinc_615a_operation(1)]
