// SPDX-License-Identifier: MPL-2.0
/**
 * @file
 * @copyright
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * @author Thomas Vogt, thomas@thomas-vogt.de
 *
 * @brief Declaration of Namespace Arinc615aDlaQt.
 **/

/**
 * @dir
 * @brief Declaration/ Definition of Namespace Arinc615aDlaQt.
 **/

#ifndef ARINC_615A_DLA_QT_ARINC615ADLAQT_HPP
#define ARINC_615A_DLA_QT_ARINC615ADLAQT_HPP

#include <arinc_615a_dla_qt/arinc_615a_dla_qt_export.h>

#include <spdlog/spdlog.h>

/**
 * @brief ARINC 615A Data Loader Application Qt (DLA) Framework.
 **/
namespace Arinc615aDlaQt {

struct DataLoaderConfiguration;

class DataLoaderMainWindow;

class SettingsDialog;

/**
 * @brief Set the logging level for the ARINC 615A DLA Qt Library.
 *
 * Adjusts the verbosity of log messages generated by the ARINC 615A DLA Qt Library.
 *
 * @param level Logging level to be set.
 *   The level defines the granularity of log messages.
 **/
ARINC_615A_DLA_QT_EXPORT void setLogLevel( spdlog::level::level_enum level );

}

#endif
