// SPDX-License-Identifier: MPL-2.0
/**
 * @file
 * @copyright
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * @author Thomas Vogt, thomas@thomas-vogt.de
 *
 * @brief Declaration of Namespace Arinc665Qt.
 **/

/**
 * @dir
 * @brief Declaration/ Definition of Namespace Arinc665Qt.
 **/

#ifndef ARINC_665_QT_ARINC665QT_HPP
#define ARINC_665_QT_ARINC665QT_HPP

#include <spdlog/spdlog.h>

#include <arinc_665_qt/arinc_665_qt_export.h>

/**
 * @brief ARINC 665 Specification Qt.
 *
 * This namespace implements Qt Models, Widgets, and Wizards to allow GUI elements for the ARINC 665 implementation.
 *
 * @sa @ref Arinc665Qt::Actions
 * @sa @ref Arinc665Qt::Media
 * @sa @ref Arinc665Qt::CompileMediaSetWizard
 * @sa @ref Arinc665Qt::DecompileMediaSetWizard
 * @sa @ref Arinc665Qt::MediaSetManager
 **/
namespace Arinc665Qt {

class MediaPathsModel;
class MediaPathsWidget;

class FilePathMappingModel;

class FileCreationPolicyModel;
class SupportedArinc665VersionModel;

/**
 * @brief Set the logging level for the ARINC 665 Qt Library.
 *
 * Adjusts the verbosity of log messages generated by the ARINC 665 Qt Library.
 *
 * @param level Logging level to be set.
 *   The level defines the granularity of log messages.
 **/
ARINC_665_QT_EXPORT void setLogLevel( spdlog::level::level_enum level );

}

#endif
