// SPDX-License-Identifier: MPL-2.0
/**
 * @file
 * @copyright
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * @author Thomas Vogt, thomas@thomas-vogt.de
 *
 * @brief Declaration of Namespace Arinc649.
 **/

/**
 * @dir
 * @brief Declaration/ Definition of Namespace Arinc649.
 **/

#ifndef ARINC_649_ARINC649_HPP
#define ARINC_649_ARINC649_HPP

#include <arinc_649/arinc_649_export.h>

#include <helper/Helper.hpp>

#include <spdlog/spdlog.h>

#include <cstdint>
#include <memory>

/**
 * @brief ARINC 649 Specification.
 *
 * This library provides an implementation, according to _ARINC 649_.
 * This standard is used within the standards _ARINC 665_ and _ARINC 615A_.
 * The main functionality is to provide common interfaces for:
 * - Checksum calculation algorithms (CRC-8, CRC-16, CRC-32, and CRC-64) see @ref Arinc649Crc.hpp
 *   (ARINC 649 Section 4.3)
 * - Check Value (ARINC 649 Section 4ff) representation and calculation @ref CheckValue and @ref CheckValueGenerator
 *   (all Checksums as above and MD5, SHA1, SHA-256, and SHA2-512), and
 * - File Naming @ref Filename.hpp (ARINC 649 Section 6.2)
 *
 * For CRC calculation, this library depends on the Boost.Crc library.
 * For the MD5, SHA, SHA-256, and SHA-512 calculation, this library depends on the Boost.Hash2 library.
 *
 * @par Referenced Documents
 * - ARINC Report 649: Common Terminology and Functions for Software Distribution and Loading; 2025-12-02
 **/
namespace Arinc649 {

//! Check Value Type Enumeration
enum class CheckValueType : uint16_t
{
  //! Not to be used
  NotUsed = 0U,
  //! 8-bit CRC (deprecated)
  //! @deprecated Use Crc32 or Crc64 instead.
  Crc8 = 1U,
  //! 16-bit CRC (deprecated)
  //! @deprecated Use Crc32 or Crc64 instead.
  Crc16 = 2U,
  //! 32-bit CRC
  Crc32 = 3U,
  //! Message-Digest Algorithm 5 (MD5)
  //! @deprecated Use Sha1, Sha256, or Sha512 instead.
  Md5 = 4U,
  //! Secure Hash Algorithm SHA1
  Sha1 = 5U,
  //! Secure Hash Algorithm SHA-256
  Sha256 = 6U,
  //! Secure Hash Algorithm SHA-512
  Sha512 = 7U,
  //! 64-bit CRC
  Crc64 = 8U
};

class CheckValue;
class CheckValueTypeDescription;
class CheckValueGenerator;

//! Check Value Generator Instance.
using CheckValueGeneratorPtr = std::shared_ptr< CheckValueGenerator >;

/**
 * @brief Returns the ARINC 649 %Version Information.
 *
 * @return %Version Information of ARINC 649 Library.
 **/
[[nodiscard]] ARINC_649_EXPORT Helper::VersionsInformation::value_type arinc649Version();

/**
 * @brief Set the logging level for the ARINC 649 Library.
 *
 * Adjusts the verbosity of log messages generated by the ARINC 649 Library.
 *
 * @param level Logging level to be set.
 *   The level defines the granularity of log messages.
 **/
ARINC_649_EXPORT void setLogLevel( spdlog::level::level_enum level );

}

#endif
