// SPDX-License-Identifier: MPL-2.0
/**
 * @file
 * @copyright
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * @author Thomas Vogt, thomas@thomas-vogt.de
 *
 * @brief Declaration of Namespace Helper.
 **/

/**
 * @dir
 * @brief Declaration/ Definition of Namespace Helper.
 *
 * @sa Namespace @ref Helper
 **/

#ifndef HELPER_HELPER_HPP
#define HELPER_HELPER_HPP

#include <helper/helper_export.h>

#include <spdlog/spdlog.h>

#include <map>
#include <string>

/**
 * @brief Common Utilities.
 *
 * The Helper Library provides common implementations for usual tasks.
 *
 * - BCD Handling (@ref Bcd.hpp)
 * - Enumeration %Description (@ref Description)
 * - Boolean %Description (@ref Bool)
 * - Endian %Description (@ref EndianDescription)
 * - Memory Dump (@ref Dump.hpp)
 * - Raw Data Handling (@ref RawData.hpp)
 * - Exception Handling (@ref Exception.hpp)
 * - Integer Bit Encoding/ Decoding (@ref NBitInteger.hpp)
 * - Parity Bit Calculation (@ref Parity.hpp)
 * - Safe Cast (@ref SafeCast.hpp)
 * - Helper Version (@ref Version)
 * - std::tuple serialisation (@ref serialize_tuple.h)
 * - boost::asio IP Address Parsing (@ref BoostAsioProgramOptions.hpp)
 * - Filename Handling (@ref Filenames.hpp)
 * - %Scheduler (@ref Scheduler)
 **/
namespace Helper {

class Scheduler;

struct VersionInformation;

//! Versions Information (Product Key => Version Information)
using VersionsInformation = std::map< std::string, VersionInformation, std::less<> >;

/**
 * @brief Return the Version Information for the Boost Library.
 *
 * @return Version Information of the Boost Library.
 **/
[[nodiscard]] HELPER_EXPORT VersionsInformation::value_type boostVersion();

/**
 * @brief Returns Helper Library Version Information
 *
 * @return Helper Library Version Information.
 **/
[[nodiscard]] HELPER_EXPORT VersionsInformation::value_type helperVersion();

/**
 * @brief Set the logging level for the Helper Library.
 *
 * Adjusts the verbosity of log messages generated by the Helper Library.
 *
 * @param level Logging level to be set.
 *   The level defines the granularity of log messages.
 **/
HELPER_EXPORT void setLogLevel( spdlog::level::level_enum level );

}

#endif
