// SPDX-License-Identifier: MPL-2.0
/**
 * @file
 * @copyright
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * @author Thomas Vogt, thomas@thomas-vogt.de
 *
 * @brief Declaration of Namespace Arinc665Commands.
 **/

/**
 * @dir
 * @brief Declaration/ Definition of Namespace Arinc665Commands
 *
 * @sa @ref Arinc665Commands
 **/

#ifndef ARINC_665_COMMANDS_ARINC665COMMANDS_HPP
#define ARINC_665_COMMANDS_ARINC665COMMANDS_HPP

#include <arinc_665_commands/arinc_665_commands_export.h>

#include <commands/Commands.hpp>

#include <spdlog/spdlog.h>

/**
 * @brief ARINC 665 %Commands.
 *
 * %Commands, which provides ARINC 665 Media Set Manager functionality by using the @ref Commands library.
 **/
namespace Arinc665Commands {

/**
 * @brief Registers the ARINC 665 %Commands to the Registry.
 *
 * @param[in,out] registry
 *   Registry, where the commands shall be registered to.
 **/
ARINC_665_COMMANDS_EXPORT void registerCommands( const Commands::CommandRegistryPtr& registry );

/**
 * @brief Set the logging level for the ARINC 665 Library.
 *
 * Adjusts the verbosity of log messages generated by the ARINC 665 Library.
 *
 * @param level Logging level to be set.
 *   The level defines the granularity of log messages.
 **/
ARINC_665_COMMANDS_EXPORT void setLogLevel( spdlog::level::level_enum level );

}

#endif
