// SPDX-License-Identifier: MPL-2.0
/**
 * @file
 * @copyright
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * @author Thomas Vogt, thomas@thomas-vogt.de
 *
 * @brief Declaration of Namespace TftpQt.
 **/

/**
 * @dir
 * @brief Declaration/ Definition of Namespace TftpQt.
 **/

#ifndef TFTP_QT_TFTPQT_HPP
#define TFTP_QT_TFTPQT_HPP

#include <tftp_qt/tftp_qt_export.h>

#include <spdlog/spdlog.h>

/**
 * @brief TFTP Qt
 **/
namespace TftpQt {

class PacketStatisticModel;

/**
 * @brief Set the logging level for the TFTP Qt Library.
 *
 * Adjusts the verbosity of log messages generated by the TFTP Qt Library.
 *
 * @param level Logging level to be set.
 *   The level defines the granularity of log messages.
 **/
TFTP_QT_EXPORT void setLogLevel( spdlog::level::level_enum level );

}

#endif
