// SPDX-License-Identifier: MPL-2.0
/**
 * @file
 * @copyright
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * @author Thomas Vogt, thomas@thomas-vogt.de
 *
 * @brief Declaration of Namespace QtIconResources.
 **/

/**
 * @dir
 * @brief Declaration/ Definition of Namespace QtIconResources.
 **/

#ifndef QT_ICON_RESOURCES_QTICONRESOURCES_HPP
#define QT_ICON_RESOURCES_QTICONRESOURCES_HPP

#include <qt_icon_resources/qt_icon_resources_export.h>

#include <helper/Helper.hpp>

#include <spdlog/spdlog.h>

/**
 * @brief Qt Icon Resources Namespace.
 *
 * To initialise the resources, call the function
 * @ref QtIconResources::initialise().
 **/
namespace QtIconResources {

/**
 * @brief Initialises the Qt Icon %Resources.
 **/
QT_ICON_RESOURCES_EXPORT void initialise();

/**
 * @brief Provide Version Qt Icon Resources Version Information.
 *
 * @return Version Information.
 **/
[[nodiscard]] QT_ICON_RESOURCES_EXPORT Helper::VersionsInformation::value_type qtIconResourcesVersion();

/**
 * @brief Set the logging level for the Qt Icon Resources Library.
 *
 * Adjusts the verbosity of log messages generated by the Qt Icon Resources Library.
 *
 * @param level Logging level to be set.
 *   The level defines the granularity of log messages.
 **/
QT_ICON_RESOURCES_EXPORT void setLogLevel( spdlog::level::level_enum level );

}

#endif
