// SPDX-License-Identifier: MPL-2.0
/**
 * @file
 * @copyright
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * @author Thomas Vogt, thomas@thomas-vogt.de
 *
 * @brief Declaration of Namespace Arinc615aCommands.
 **/

/**
 * @dir
 * @brief Declaration/ Definition of Namespace Arinc615aCommands.
 **/

#ifndef ARINC_615A_COMMANDS_ARINC615ACOMMANDS_HPP
#define ARINC_615A_COMMANDS_ARINC615ACOMMANDS_HPP

#include <arinc_615a_commands/arinc_615a_commands_export.h>

#include <commands/Commands.hpp>

#include <spdlog/spdlog.h>

#include <boost/asio/ip/address.hpp>

#include <boost/asio/io_context.hpp>

#include <boost/program_options/options_description.hpp>

#include <boost/signals2/signal.hpp>

/**
 * @brief ARINC 615A %Commands.
 *
 * %Commands, which provide Host Data Loader Functions:
 * - @ref Targets::FindQueryCommand,
 * - @ref Targets::ListTargetsCommand,
 * - @ref Operations::InformationOperationCommand,
 * - @ref Operations::UploadOperationCommand,
 * - @ref Operations::MediaDefinedDownloadOperationCommand, and
 * - @ref Operations::OperatorDefinedDownloadOperationCommand.
 *
 * These classes can be used to be registered to @ref Commands::CommandRegistry instances or call
 * @ref Arinc615aCommands::registerCommands().
 *
 * @sa @ref Commands
 **/
namespace Arinc615aCommands {

//! Signal raised when the application is aborted or terminated
using AbortTerminateSignal = boost::signals2::signal< void() >;

/**
 * @brief Registers the ARINC 615A %Commands to the Registry.
 *
 * @param[in,out] registry
 *   Command registry.
 * @param[in] ioContext
 *   I/O Context used of operations.
 * @param[in] abortSignal
 *   Signal raised when application is aborted.
 * @param[in] terminateSignal
 *   Signal raised when application is terminated.
 *   Registry, where the commands shall be registered to.
 **/
ARINC_615A_COMMANDS_EXPORT void registerCommands(
  const Commands::CommandRegistryPtr &registry,
  boost::asio::io_context &ioContext,
  AbortTerminateSignal &abortSignal,
  AbortTerminateSignal &terminateSignal );

/**
 * @brief Return _Target Address_ Command Line Option.
 *
 * @param[in,out] targetAddress
 *   Pointer to variable, which will be filled with target IP address on parsing.
 * @param[in] defaultIsBroadcast
 *   If set to `true`, the default value will be set to the IPV4 broadcast address.
 *
 * @return Target Address command line option description.
 **/
[[nodiscard]] ARINC_615A_COMMANDS_EXPORT boost::shared_ptr< boost::program_options::option_description > targetAddress(
  boost::asio::ip::address * targetAddress,
  bool defaultIsBroadcast = false );

/**
 * @brief Set the logging level for the ARINC 615A Commands Library.
 *
 * Adjusts the verbosity of log messages generated by the ARINC 615A Commands Library.
 *
 * @param level Logging level to be set.
 *   The level defines the granularity of log messages.
 **/
ARINC_615A_COMMANDS_EXPORT void setLogLevel( spdlog::level::level_enum level );

}

#endif
