// SPDX-License-Identifier: MPL-2.0
/**
 * @file
 * @copyright
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * @author Thomas Vogt, thomas@thomas-vogt.de
 *
 * @brief Declaration of Namespace Commands.
 **/

/**
 * @dir
 * @brief Declaration/ Definition of Namespace Commands.
 **/

#ifndef COMMANDS_COMMANDS_HPP
#define COMMANDS_COMMANDS_HPP

#include <commands/commands_export.h>

#include <helper/Helper.hpp>

#include <spdlog/spdlog.h>

#include <functional>
#include <memory>
#include <string>
#include <vector>

/**
 * @brief Generic Command Registry.
 *
 * This framework is used to register commands, which are executed on request.
 *
 * @sa @ref CommandRegistry
 **/
namespace Commands {

class CommandRegistry;

//! Command Parameters
using Parameters = std::vector< std::string >;

/**
 * @brief Command execute function
 *
 * @param[in] parameters
 *   Command parameters
 **/
using ExecuteFunction = std::function< void( const Parameters &parameters ) >;

//! Command help function
using HelpFunction = std::function< void() >;

//! Command Registry Instance
using CommandRegistryPtr = std::shared_ptr< CommandRegistry >;

/**
 * @brief Command Line Handler.
 *
 * This handler is compliant to `int main(argc,argv)`.
 *
 * @param[in] argc
 *   Argument Count.
 *   Number of elements within @p argv.
 * @param[in] argv
 *   Array of arguments.
 *
 * @return Return Code.
 **/
using CommandLineHandler = std::function< int( int argc, char const * const argv[] ) >;

/**
 * @brief Returns %Commands Library %Version Information.
 *
 * @return %Version Information.
 **/
[[nodiscard]] COMMANDS_EXPORT Helper::VersionsInformation::value_type commandsVersion();

/**
 * @brief Set the logging level for the Commands Library.
 *
 * Adjusts the verbosity of log messages generated by the Commands Library.
 *
 * @param level Logging level to be set.
 *   The level defines the granularity of log messages.
 **/
COMMANDS_EXPORT void setLogLevel( spdlog::level::level_enum level );

}

#endif
