[[man_arinc_615a_download_request_file]]
= arinc_615a_download_request_file(1)
Thomas Vogt

== Name

arinc_615a_download_request_file - generates an ARINC 615A Download Request file.

== Synopsis

*arinc_615a_download_request_file*
--filename _filename_
{--download-file _filename_}
[--user-defined-data _string_]
[--arinc615a-version Arinc615a2|Arinc615a34]

== Options

// tag::options[]
*--filename* _filename_::
ARINC 615A Download Request file to create.

*--download-file* _filename_::
One or more filenames to be downloaded.
May be specified multiple times.

*--user-defined-data* _string_::
String to include as _user-defined data_.

*--arinc615a-version* Arinc615a2|Arinc615a34::
ARINC 615A protocol version.
* `Arinc615a2` Defines ARINC 615A-2
* `Arinc615a34` Defines ARINC 615A-3 and ARINC 615A-4

== Examples

.Basic: request a single file
[source,shell]
----
arinc_615a_download_request_file \
  --filename request.a615a \
  --download-file avionics.cfg
----

.Request multiple files (repeat --download-file)
[source,shell]
----
arinc_615a_download_request_file \
  --filename request_multi.LNR \
  --download-file part1.bin \
  --download-file part2.bin \
  --download-file docs/readme.txt
----

.Include user-defined data
[source,shell]
----
arinc_615a_download_request_file \
  --filename request_ud.LNR \
  --download-file nav.db \
  --user-defined-data "Test run 2025-09-02"
----

.Specify ARINC 615A protocol version 2
[source,shell]
----
arinc_615a_download_request_file \
  --filename request_v2.LNR \
  --download-file firmware.bin \
  --arinc615a-version Arinc615a2
----

.Specify ARINC 615A protocol version 3/4
[source,shell]
----
arinc_615a_download_request_file \
  --filename request_v34.LNR \
  --download-file firmware.bin \
  --arinc615a-version Arinc615a34
----

== See Also

link:[arinc_615a_operation(1)]
