# SPDX-License-Identifier: MPL-2.0
cmake_minimum_required(VERSION 3.24)
set(PROJECT_SOURCE_DIR "${SOURCE_DIR}")
include("${SOURCE_DIR}/cmake/TargetSources.cmake")
set(expected)
foreach(name helper arinc_649 arinc_665 tftp arinc_615a arinc_615a_test_tha_lib)
  list(APPEND expected ${${name}_SOURCES})
endforeach()
file(READ "${BUILD_DIR}/compile_commands.json" commands)
string(JSON count LENGTH "${commands}")
math(EXPR last "${count} - 1")
set(compiled)
foreach(i RANGE 0 ${last})
  string(JSON source GET "${commands}" ${i} file)
  if(source IN_LIST expected)
    list(APPEND compiled "${source}")
    string(JSON command GET "${commands}" ${i} command)
    if(NOT command MATCHES "ARINC_615A_NO_PROGRAM_OPTIONS" OR command MATCHES "std=c\\+\\+17")
      message(FATAL_ERROR "Incorrect target compile flags: ${source}")
    endif()
  elseif(NOT source MATCHES "/(test|tests)/")
    message(FATAL_ERROR "Unexpected source in target build: ${source}")
  endif()
endforeach()
list(REMOVE_DUPLICATES compiled)
list(LENGTH expected expected_count)
list(LENGTH compiled compiled_count)
if(NOT compiled_count EQUAL expected_count)
  message(FATAL_ERROR "Target manifest differs from compiled source list")
endif()

set(forbidden_symbols "boost::(program_options|filesystem|thread)|xmlpp::|Qt[0-9]?::|spdlog::details::thread_pool")
file(GLOB archives "${BUILD_DIR}/lib/*${SUFFIX}")
list(LENGTH archives archive_count)
if(NOT archive_count EQUAL 6)
  message(FATAL_ERROR "Expected six target archives, found ${archive_count}")
endif()
set(symbol_report "")
foreach(archive IN LISTS archives)
  execute_process(COMMAND "${NM}" -u -C "${archive}" RESULT_VARIABLE status OUTPUT_VARIABLE symbols ERROR_VARIABLE errors)
  if(NOT status EQUAL 0)
    message(FATAL_ERROR "Cannot audit ${archive}: ${errors}")
  endif()
  if(symbols MATCHES "${forbidden_symbols}")
    message(FATAL_ERROR "Forbidden desktop dependency in ${archive}: ${CMAKE_MATCH_0}")
  endif()
  string(APPEND symbol_report "${archive}\n${symbols}\n")
endforeach()
file(WRITE "${BUILD_DIR}/target-undefined-symbols.txt" "${symbol_report}")
if(GENERATOR MATCHES "Ninja")
  execute_process(COMMAND "${MAKE_TOOL}" -t deps WORKING_DIRECTORY "${BUILD_DIR}"
    RESULT_VARIABLE status OUTPUT_VARIABLE deps ERROR_VARIABLE errors)
  if(NOT status EQUAL 0)
    message(FATAL_ERROR "Cannot audit compiler header dependencies: ${errors}")
  endif()
  if(deps MATCHES "boost/(program_options|filesystem|thread)/|libxml[+][+]|qt_icon_resources/lib/|commands/lib/")
    message(FATAL_ERROR "Forbidden desktop header in compiler dependencies: ${CMAKE_MATCH_0}")
  endif()
  file(WRITE "${BUILD_DIR}/target-header-dependencies.txt" "${deps}")
endif()
file(WRITE "${BUILD_DIR}/DEPENDENCY_AUDIT.txt"
  "PASS: ${compiled_count} target source files; six static libraries.\nNo compiled Boost program_options/filesystem/thread, Qt, XML or command framework references.\nUndefined symbols in individual archives include cross-library references and SDK/runtime symbols; see target-undefined-symbols.txt.\nA successful SDK DKM link is still required.\n")
message(STATUS "Target dependency audit passed: ${compiled_count} source files, ${archive_count} archives")
